[features]
seeds = true
skip-lint = false
resolution = true

[programs.localnet]
pvp_game = "PVPgame11111111111111111111111111111111111"

[programs.devnet]
pvp_game = "PVPgame11111111111111111111111111111111111"

[programs.mainnet]
pvp_game = "PVPgame11111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.devnet.solana.com"

[workspace]
members = ["programs/*"]
